In [1]:
import pandas as pd
import numpy as np

In [2]:
netflix_df = pd.read_csv("netflix_titles_corrected.csv")
netflix_df.head()

,show_id,type,title,director,cast,country,date_added_corrected,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",9/9/19,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,9/9/16,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,9/8/18,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,9/8/18,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,9/8/17,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
# new data frame with split value columns 
file = netflix_df["listed_in"].str.split(",", n = 1, expand = True)
print(netflix_df.count())

show_id                 6234
type                    6234
title                   6234
director                4265
cast                    5664
country                 5758
date_added_corrected    6223
release_year            6234
rating                  6224
duration                6234
listed_in               6234
description             6234
dtype: int64

In [4]:
# making separate genre category column from new data frame 
netflix_df["Genre Main Category"] = file[0]

In [5]:
# making separate sub category column from new data frame
netflix_df["Genre Sub Category"]= file[1]

In [6]:
netflix_df["year added"] = ""
netflix_df['date_added_corrected'] = pd.to_datetime(netflix_df['date_added_corrected'])
netflix_df['year added'] = netflix_df['date_added_corrected'].dt.year

In [7]:
netflix_df.head()

,show_id,type,title,director,cast,country,date_added_corrected,release_year,rating,duration,listed_in,description,Genre Main Category,Genre Sub Category,year added
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,Children & Family Movies,Comedies,2019.0
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09-09,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,Stand-Up Comedy,None,2016.0
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",Kids' TV,None,2018.0
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,Kids' TV,None,2018.0
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09-08,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,Comedies,None,2017.0